version: '3.3'
networks:
  web:
    external: true
volumes:
  grafana-storage:
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - '3000:3000'
    environment:
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.sendgrid.net:587
      - GF_SMTP_USER=apikey
      - GF_SMTP_PASSWORD=
      - GF_SMTP_FROM_ADDRESS=
      - GF_SMTP_FROM_NAME=Grafana
      - GF_SMTP_EHLO_IDENTITY=
      - GF_SMTP_STARTTLS_POLICY=MandatoryStartTLS
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`yourhosthere`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    networks:
      - web      
